### ISSUE TITLE
Numpy raises TypeError when using python3

### ISSUE THREAD

**Issue by iuvenis** [Marcello-Sega/pytim#333]
Having installed from pip and running the script
```
import MDAnalysis as mda
import pytim
from   pytim.datafiles import *

u = mda.Universe(WATER_GRO, format='gro')

interface = pytim.ITIM(u)
```
I get the error message
```
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/numpy/core/function_base.py", line 117, in linspace
    num = operator.index(num)
TypeError: 'numpy.float64' object cannot be interpreted as an integer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tutorial.txt", line 7, in <module>
    interface = pytim.ITIM(u)
  File "/home/iuvenis/.local/lib/python3.8/site-packages/pytim/itim.py", line 218, in __init__
    self._assign_layers()
  File "/home/iuvenis/.local/lib/python3.8/site-packages/pytim/itim.py", line 358, in _assign_layers
    self._prepare_layers_assignment()
  File "/home/iuvenis/.local/lib/python3.8/site-packages/pytim/itim.py", line 317, in _prepare_layers_assignment
    self._assign_mesh()
  File "/home/iuvenis/.local/lib/python3.8/site-packages/pytim/itim.py", line 235, in _assign_mesh
    _x = np.linspace(0, box[0], num=self.mesh_nx, endpoint=False)
  File "<__array_function__ internals>", line 5, in linspace
  File "/usr/lib/python3.8/site-packages/numpy/core/function_base.py", line 119, in linspace
    raise TypeError(
TypeError: object of type <class 'numpy.float64'> cannot be safely interpreted as an integer.
```
on python3.8.
The script works fine on 2.7.18 on the other hand.

**Comment by iuvenis** [comment]
When installing from the git repository the above example worked under python3 as well.

I am now encountering a very similar error in the WillardChandler tutorial though.
The minimal example is
```
import pytim
from pytim.datafiles import *
import MDAnalysis as mda
u = mda.Universe(MICELLE_PDB)
g = u.select_atoms('resname DPC')
interface = pytim.WillardChandler(u, group=g, mesh=1.5, alpha=3.0)
```
and the error (using python3 and the git repo version of pytim):
```
File "tutorial_wc.py", line 8, in <module>
    interface = pytim.WillardChandler(u, group=g, mesh=1.5, alpha=3.0)
  File "/home/iuvenis/.local/lib/python3.8/site-packages/pytim-0.8.1-py3.8-linux-x86_64.egg/pytim/willard_chandler.py", line 131, in __init__
    self._assign_layers()
  File "/home/iuvenis/.local/lib/python3.8/site-packages/pytim-0.8.1-py3.8-linux-x86_64.egg/pytim/willard_chandler.py", line 213, in _assign_layers
    grid = utilities.generate_grid_in_box(box, ngrid, order='xyz')
  File "/home/iuvenis/.local/lib/python3.8/site-packages/pytim-0.8.1-py3.8-linux-x86_64.egg/pytim/utilities_mesh.py", line 26, in generate_grid_in_box
    xyz.append(np.linspace(0., box[i] - box[i] / npoints[i], npoints[i]))
  File "<__array_function__ internals>", line 5, in linspace
  File "/usr/lib/python3.8/site-packages/numpy/core/function_base.py", line 119, in linspace
    raise TypeError(
TypeError: object of type <class 'numpy.float64'> cannot be safely interpreted as an integer.
```

**Comment by iuvenis** [comment]
Found a fix for the problem in the git repo version and opened pull request #334 for it.
